; UART <-> CAN (SLCAN) bridge, listen-only
; Target: ESP32-C3 SuperMini + SN65HVD230 transceiver

[env:esp32c3_supermini]
platform = espressif32@^6.9.0
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=0
    -DCAN_TX_PIN=2
    -DCAN_RX_PIN=3
    -DUART_RX_PIN=0
    -DUART_TX_PIN=1
    -DUART_BAUD=750000            ; nearest with used 24MHz clock on F133 
    -DDEFAULT_CAN_SPEED_IDX=3     ; SLCAN S3 = 100 kbit/s
    -DAUTO_OPEN=1                 ; start listening at boot without needing 'O'